name: autofix.ci # needed to securely identify the workflow

on:
  pull_request:
  push:
    branches: ['main']
permissions:
  contents: read

jobs:
  lint-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Install Bun
        uses: oven-sh/setup-bun@0c5077e51419868618aeaa5fe8019c62421857d6 # v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Format with Prettier
        run: bunx prettier -w . "!.github"

      - name: Run autofix.ci
        uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a # v1.3
